
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Geek Cookies.
tagline:             'the Dark Side of the Geek.'
description:         'Join the Dark Side of the Geek: we have Cookies.'
url:                 http://geekcookies.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Geek Cookies
  url:               https://twitter.com/geekcookiescast
  email:             geekcookiespodcast@gmail.com

# Custom vars
version:             1.0.0

future: false
permalink: pretty
markdown: rdiscount

exclude:
- README.md

podcast:
  owner:
    name: Geek Cookies 
    email: geekcookiespodcast@gmail.com 
  explicit: "no"
  image: http://geekcookies.github.io/images/icon.png 
  category: CATEGORIA
  subtitle: 'Join the Dark Side of the Geek: we have Cookies.'
  defaultFileType: audio/mpeg
  year: 2014

#flattr:
  #uid: 

disqus:
  shortname: geekcookies

google:
  analytics:
    tracking_id: UA-56320158-1 
    domain_name: geekcookies.github.io 


#Add a list of enabled gems (plugins) to your site's _config.yml file, such as:
gems:
    #- jek yll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-sitemap
